// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_accumulate_matrix
Rcpp::List cpp_accumulate_matrix(SEXP ptr, const arma::mat& G, int block_size);
RcppExport SEXP _spatialGPCA_cpp_accumulate_matrix(SEXP ptrSEXP, SEXP GSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_accumulate_matrix(ptr, G, block_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_accumulate_file
Rcpp::List cpp_accumulate_file(SEXP ptr, std::string path, Rcpp::IntegerVector locations, const arma::vec& af, int block_size);
RcppExport SEXP _spatialGPCA_cpp_accumulate_file(SEXP ptrSEXP, SEXP pathSEXP, SEXP locationsSEXP, SEXP afSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type af(afSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_accumulate_file(ptr, path, locations, af, block_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_info
Rcpp::List cpp_info(SEXP ptr);
RcppExport SEXP _spatialGPCA_cpp_info(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_info(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_statistics
Rcpp::List cpp_statistics(SEXP ptr);
RcppExport SEXP _spatialGPCA_cpp_statistics(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_statistics(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_snapshot
Rcpp::List cpp_snapshot(SEXP ptr);
RcppExport SEXP _spatialGPCA_cpp_snapshot(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_snapshot(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_restore
SEXP cpp_restore(Rcpp::List s);
RcppExport SEXP _spatialGPCA_cpp_restore(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_restore(s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit
Rcpp::List cpp_fit(SEXP ptr, std::string method, Rcpp::CharacterVector operators, int components, double fixed_lambda);
RcppExport SEXP _spatialGPCA_cpp_fit(SEXP ptrSEXP, SEXP methodSEXP, SEXP operatorsSEXP, SEXP componentsSEXP, SEXP fixed_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type operators(operatorsSEXP);
    Rcpp::traits::input_parameter< int >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< double >::type fixed_lambda(fixed_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit(ptr, method, operators, components, fixed_lambda));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fitted
arma::mat cpp_fitted(SEXP ptr, const arma::mat& G, double lambda, bool coefficients);
RcppExport SEXP _spatialGPCA_cpp_fitted(SEXP ptrSEXP, SEXP GSEXP, SEXP lambdaSEXP, SEXP coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type coefficients(coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fitted(ptr, G, lambda, coefficients));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cluster
Rcpp::List cpp_cluster(const arma::mat& xy, int m, int seed);
RcppExport SEXP _spatialGPCA_cpp_cluster(SEXP xySEXP, SEXP mSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xy(xySEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cluster(xy, m, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prepare
SEXP cpp_prepare(const arma::mat& xy, const arma::mat& pcs, const arma::vec& counts, const arma::mat& knots, double rho);
RcppExport SEXP _spatialGPCA_cpp_prepare(SEXP xySEXP, SEXP pcsSEXP, SEXP countsSEXP, SEXP knotsSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xy(xySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pcs(pcsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prepare(xy, pcs, counts, knots, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spatialGPCA_cpp_accumulate_matrix", (DL_FUNC) &_spatialGPCA_cpp_accumulate_matrix, 3},
    {"_spatialGPCA_cpp_accumulate_file", (DL_FUNC) &_spatialGPCA_cpp_accumulate_file, 5},
    {"_spatialGPCA_cpp_info", (DL_FUNC) &_spatialGPCA_cpp_info, 1},
    {"_spatialGPCA_cpp_statistics", (DL_FUNC) &_spatialGPCA_cpp_statistics, 1},
    {"_spatialGPCA_cpp_snapshot", (DL_FUNC) &_spatialGPCA_cpp_snapshot, 1},
    {"_spatialGPCA_cpp_restore", (DL_FUNC) &_spatialGPCA_cpp_restore, 1},
    {"_spatialGPCA_cpp_fit", (DL_FUNC) &_spatialGPCA_cpp_fit, 5},
    {"_spatialGPCA_cpp_fitted", (DL_FUNC) &_spatialGPCA_cpp_fitted, 4},
    {"_spatialGPCA_cpp_cluster", (DL_FUNC) &_spatialGPCA_cpp_cluster, 3},
    {"_spatialGPCA_cpp_prepare", (DL_FUNC) &_spatialGPCA_cpp_prepare, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spatialGPCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
