# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_accumulate_matrix <- function(ptr, G, block_size) {
    .Call(`_spatialGPCA_cpp_accumulate_matrix`, ptr, G, block_size)
}

cpp_accumulate_file <- function(ptr, path, locations, af, block_size) {
    .Call(`_spatialGPCA_cpp_accumulate_file`, ptr, path, locations, af, block_size)
}

cpp_info <- function(ptr) {
    .Call(`_spatialGPCA_cpp_info`, ptr)
}

cpp_statistics <- function(ptr) {
    .Call(`_spatialGPCA_cpp_statistics`, ptr)
}

cpp_snapshot <- function(ptr) {
    .Call(`_spatialGPCA_cpp_snapshot`, ptr)
}

cpp_restore <- function(s) {
    .Call(`_spatialGPCA_cpp_restore`, s)
}

cpp_fit <- function(ptr, method, operators, components, fixed_lambda) {
    .Call(`_spatialGPCA_cpp_fit`, ptr, method, operators, components, fixed_lambda)
}

cpp_fitted <- function(ptr, G, lambda, coefficients) {
    .Call(`_spatialGPCA_cpp_fitted`, ptr, G, lambda, coefficients)
}

cpp_cluster <- function(xy, m, seed) {
    .Call(`_spatialGPCA_cpp_cluster`, xy, m, seed)
}

cpp_prepare <- function(xy, pcs, counts, knots, rho) {
    .Call(`_spatialGPCA_cpp_prepare`, xy, pcs, counts, knots, rho)
}

cpp_spde_project <- function(xy, tv, loc) {
    .Call(`_spatialGPCA_cpp_spde_project`, xy, tv, loc)
}

cpp_spde_accumulate_matrix <- function(B, Xq, counts, G, block_size, projection) {
    .Call(`_spatialGPCA_cpp_spde_accumulate_matrix`, B, Xq, counts, G, block_size, projection)
}

cpp_spde_accumulate_reader <- function(B, Xq, counts, reader, p, block_size, projection) {
    .Call(`_spatialGPCA_cpp_spde_accumulate_reader`, B, Xq, counts, reader, p, block_size, projection)
}

cpp_spde_accumulate_bed <- function(B, Xq, counts, path, locations, af, block_size, projection) {
    .Call(`_spatialGPCA_cpp_spde_accumulate_bed`, B, Xq, counts, path, locations, af, block_size, projection)
}

